# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1  # noqa: E501

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.second_market_buy_request import SecondMarketBuyRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestSecondMarketBuyRequest(unittest.TestCase):
    """SecondMarketBuyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecondMarketBuyRequest(self):
        """Test SecondMarketBuyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.second_market_buy_request.SecondMarketBuyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
