# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1  # noqa: E501

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bondora_api
from bondora_api.api.second_market_api import SecondMarketApi  # noqa: E501
from bondora_api.rest import ApiException


class TestSecondMarketApi(unittest.TestCase):
    """SecondMarketApi unit test stubs"""

    def setUp(self):
        self.api = bondora_api.api.second_market_api.SecondMarketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_second_market_buy(self):
        """Test case for second_market_buy

        Buy loans from secondary market.  # noqa: E501
        """
        pass

    def test_second_market_cancel(self):
        """Test case for second_market_cancel

        Remove your loans from secondary market.  # noqa: E501
        """
        pass

    def test_second_market_cancel_multiple(self):
        """Test case for second_market_cancel_multiple

        Remove your loans from secondary market.  # noqa: E501
        """
        pass

    def test_second_market_get(self):
        """Test case for second_market_get

        Gets LoanPartDetails info by identifier  # noqa: E501
        """
        pass

    def test_second_market_get_active(self):
        """Test case for second_market_get_active

        Gets list of active secondary market items  # noqa: E501
        """
        pass

    def test_second_market_get_item(self):
        """Test case for second_market_get_item

        Get the secondary market item summary  # noqa: E501
        """
        pass

    def test_second_market_get_item_list(self):
        """Test case for second_market_get_item_list

        Get the secondary market item summaries in a list  # noqa: E501
        """
        pass

    def test_second_market_get_item_list_0(self):
        """Test case for second_market_get_item_list_0

        Get the secondary market item summaries in a list  # noqa: E501
        """
        pass

    def test_second_market_get_list(self):
        """Test case for second_market_get_list

        Gets LoanPartDetails info by identifiers in a list (up to 1000 items).  # noqa: E501
        """
        pass

    def test_second_market_get_list_0(self):
        """Test case for second_market_get_list_0

        Gets LoanPartDetails info by identifiers in a list (up to 1000 items).  # noqa: E501
        """
        pass

    def test_second_market_sell(self):
        """Test case for second_market_sell

        Sell your loans to secondary market.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
