# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1  # noqa: E501

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.auction_extended import AuctionExtended  # noqa: E501
from swagger_client.rest import ApiException


class TestAuctionExtended(unittest.TestCase):
    """AuctionExtended unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuctionExtended(self):
        """Test AuctionExtended"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.auction_extended.AuctionExtended()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
