# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1  # noqa: E501

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.auction_api import AuctionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuctionApi(unittest.TestCase):
    """AuctionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.auction_api.AuctionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auction_get(self):
        """Test case for auction_get

        Gets Auction info by auction identifier  # noqa: E501
        """
        pass

    def test_auction_get_active(self):
        """Test case for auction_get_active

        Gets list of active Auctions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
