# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1  # noqa: E501

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.liability import Liability  # noqa: E501
from swagger_client.rest import ApiException


class TestLiability(unittest.TestCase):
    """Liability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiability(self):
        """Test Liability"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.liability.Liability()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
