# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1  # noqa: E501

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bondora_api
from bondora_api.models.report_create_request import ReportCreateRequest  # noqa: E501
from bondora_api.rest import ApiException


class TestReportCreateRequest(unittest.TestCase):
    """ReportCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportCreateRequest(self):
        """Test ReportCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bondora_api.models.report_create_request.ReportCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
