# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1  # noqa: E501

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SecondMarketSaleResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'loan_part_id': 'str',
        'desired_discount_rate': 'int'
    }

    attribute_map = {
        'id': 'Id',
        'loan_part_id': 'LoanPartId',
        'desired_discount_rate': 'DesiredDiscountRate'
    }

    def __init__(self, id=None, loan_part_id=None, desired_discount_rate=None):  # noqa: E501
        """SecondMarketSaleResponse - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._loan_part_id = None
        self._desired_discount_rate = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if loan_part_id is not None:
            self.loan_part_id = loan_part_id
        if desired_discount_rate is not None:
            self.desired_discount_rate = desired_discount_rate

    @property
    def id(self):
        """Gets the id of this SecondMarketSaleResponse.  # noqa: E501

        Item unique identifier  # noqa: E501

        :return: The id of this SecondMarketSaleResponse.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SecondMarketSaleResponse.

        Item unique identifier  # noqa: E501

        :param id: The id of this SecondMarketSaleResponse.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def loan_part_id(self):
        """Gets the loan_part_id of this SecondMarketSaleResponse.  # noqa: E501

        Secondary market item unique identifier  # noqa: E501

        :return: The loan_part_id of this SecondMarketSaleResponse.  # noqa: E501
        :rtype: str
        """
        return self._loan_part_id

    @loan_part_id.setter
    def loan_part_id(self, loan_part_id):
        """Sets the loan_part_id of this SecondMarketSaleResponse.

        Secondary market item unique identifier  # noqa: E501

        :param loan_part_id: The loan_part_id of this SecondMarketSaleResponse.  # noqa: E501
        :type: str
        """

        self._loan_part_id = loan_part_id

    @property
    def desired_discount_rate(self):
        """Gets the desired_discount_rate of this SecondMarketSaleResponse.  # noqa: E501

        Desired discount rate  # noqa: E501

        :return: The desired_discount_rate of this SecondMarketSaleResponse.  # noqa: E501
        :rtype: int
        """
        return self._desired_discount_rate

    @desired_discount_rate.setter
    def desired_discount_rate(self, desired_discount_rate):
        """Sets the desired_discount_rate of this SecondMarketSaleResponse.

        Desired discount rate  # noqa: E501

        :param desired_discount_rate: The desired_discount_rate of this SecondMarketSaleResponse.  # noqa: E501
        :type: int
        """
        if desired_discount_rate is not None and desired_discount_rate > 40:  # noqa: E501
            raise ValueError("Invalid value for `desired_discount_rate`, must be a value less than or equal to `40`")  # noqa: E501
        if desired_discount_rate is not None and desired_discount_rate < -100:  # noqa: E501
            raise ValueError("Invalid value for `desired_discount_rate`, must be a value greater than or equal to `-100`")  # noqa: E501

        self._desired_discount_rate = desired_discount_rate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SecondMarketSaleResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SecondMarketSaleResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
