# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1  # noqa: E501

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ScheduledPayment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scheduled_date': 'datetime',
        'principal_amount': 'float',
        'principal_amount_left': 'float',
        'interest_amount': 'float',
        'intrest_amount_carried_over': 'float',
        'penalty_amount_carried_over': 'float',
        'total_amount': 'float'
    }

    attribute_map = {
        'scheduled_date': 'ScheduledDate',
        'principal_amount': 'PrincipalAmount',
        'principal_amount_left': 'PrincipalAmountLeft',
        'interest_amount': 'InterestAmount',
        'intrest_amount_carried_over': 'IntrestAmountCarriedOver',
        'penalty_amount_carried_over': 'PenaltyAmountCarriedOver',
        'total_amount': 'TotalAmount'
    }

    def __init__(self, scheduled_date=None, principal_amount=None, principal_amount_left=None, interest_amount=None, intrest_amount_carried_over=None, penalty_amount_carried_over=None, total_amount=None):  # noqa: E501
        """ScheduledPayment - a model defined in Swagger"""  # noqa: E501

        self._scheduled_date = None
        self._principal_amount = None
        self._principal_amount_left = None
        self._interest_amount = None
        self._intrest_amount_carried_over = None
        self._penalty_amount_carried_over = None
        self._total_amount = None
        self.discriminator = None

        if scheduled_date is not None:
            self.scheduled_date = scheduled_date
        if principal_amount is not None:
            self.principal_amount = principal_amount
        if principal_amount_left is not None:
            self.principal_amount_left = principal_amount_left
        if interest_amount is not None:
            self.interest_amount = interest_amount
        if intrest_amount_carried_over is not None:
            self.intrest_amount_carried_over = intrest_amount_carried_over
        if penalty_amount_carried_over is not None:
            self.penalty_amount_carried_over = penalty_amount_carried_over
        if total_amount is not None:
            self.total_amount = total_amount

    @property
    def scheduled_date(self):
        """Gets the scheduled_date of this ScheduledPayment.  # noqa: E501

        Scheduled payment date  # noqa: E501

        :return: The scheduled_date of this ScheduledPayment.  # noqa: E501
        :rtype: datetime
        """
        return self._scheduled_date

    @scheduled_date.setter
    def scheduled_date(self, scheduled_date):
        """Sets the scheduled_date of this ScheduledPayment.

        Scheduled payment date  # noqa: E501

        :param scheduled_date: The scheduled_date of this ScheduledPayment.  # noqa: E501
        :type: datetime
        """

        self._scheduled_date = scheduled_date

    @property
    def principal_amount(self):
        """Gets the principal_amount of this ScheduledPayment.  # noqa: E501

        Scheduled principal amount  # noqa: E501

        :return: The principal_amount of this ScheduledPayment.  # noqa: E501
        :rtype: float
        """
        return self._principal_amount

    @principal_amount.setter
    def principal_amount(self, principal_amount):
        """Sets the principal_amount of this ScheduledPayment.

        Scheduled principal amount  # noqa: E501

        :param principal_amount: The principal_amount of this ScheduledPayment.  # noqa: E501
        :type: float
        """

        self._principal_amount = principal_amount

    @property
    def principal_amount_left(self):
        """Gets the principal_amount_left of this ScheduledPayment.  # noqa: E501

        Scheduled principal amount remaining after payment  # noqa: E501

        :return: The principal_amount_left of this ScheduledPayment.  # noqa: E501
        :rtype: float
        """
        return self._principal_amount_left

    @principal_amount_left.setter
    def principal_amount_left(self, principal_amount_left):
        """Sets the principal_amount_left of this ScheduledPayment.

        Scheduled principal amount remaining after payment  # noqa: E501

        :param principal_amount_left: The principal_amount_left of this ScheduledPayment.  # noqa: E501
        :type: float
        """

        self._principal_amount_left = principal_amount_left

    @property
    def interest_amount(self):
        """Gets the interest_amount of this ScheduledPayment.  # noqa: E501

        Scheduled interest amount  # noqa: E501

        :return: The interest_amount of this ScheduledPayment.  # noqa: E501
        :rtype: float
        """
        return self._interest_amount

    @interest_amount.setter
    def interest_amount(self, interest_amount):
        """Sets the interest_amount of this ScheduledPayment.

        Scheduled interest amount  # noqa: E501

        :param interest_amount: The interest_amount of this ScheduledPayment.  # noqa: E501
        :type: float
        """

        self._interest_amount = interest_amount

    @property
    def intrest_amount_carried_over(self):
        """Gets the intrest_amount_carried_over of this ScheduledPayment.  # noqa: E501

        Interest amount carried over from rescheduling  # noqa: E501

        :return: The intrest_amount_carried_over of this ScheduledPayment.  # noqa: E501
        :rtype: float
        """
        return self._intrest_amount_carried_over

    @intrest_amount_carried_over.setter
    def intrest_amount_carried_over(self, intrest_amount_carried_over):
        """Sets the intrest_amount_carried_over of this ScheduledPayment.

        Interest amount carried over from rescheduling  # noqa: E501

        :param intrest_amount_carried_over: The intrest_amount_carried_over of this ScheduledPayment.  # noqa: E501
        :type: float
        """

        self._intrest_amount_carried_over = intrest_amount_carried_over

    @property
    def penalty_amount_carried_over(self):
        """Gets the penalty_amount_carried_over of this ScheduledPayment.  # noqa: E501

        Penalty amount carried over from rescheduling  # noqa: E501

        :return: The penalty_amount_carried_over of this ScheduledPayment.  # noqa: E501
        :rtype: float
        """
        return self._penalty_amount_carried_over

    @penalty_amount_carried_over.setter
    def penalty_amount_carried_over(self, penalty_amount_carried_over):
        """Sets the penalty_amount_carried_over of this ScheduledPayment.

        Penalty amount carried over from rescheduling  # noqa: E501

        :param penalty_amount_carried_over: The penalty_amount_carried_over of this ScheduledPayment.  # noqa: E501
        :type: float
        """

        self._penalty_amount_carried_over = penalty_amount_carried_over

    @property
    def total_amount(self):
        """Gets the total_amount of this ScheduledPayment.  # noqa: E501

        Total payment amount  # noqa: E501

        :return: The total_amount of this ScheduledPayment.  # noqa: E501
        :rtype: float
        """
        return self._total_amount

    @total_amount.setter
    def total_amount(self, total_amount):
        """Sets the total_amount of this ScheduledPayment.

        Total payment amount  # noqa: E501

        :param total_amount: The total_amount of this ScheduledPayment.  # noqa: E501
        :type: float
        """

        self._total_amount = total_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScheduledPayment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduledPayment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
